# ./Playbooks/buildOpenSSL-CTL.yml

- hosts: ossl 
  gather_facts: true
  tasks:
  - name: Copy SPEC file to tmp location
    copy: src=copyfiles/openssl.spec dest=/tmp/
          owner=root group=root mode=0500
  - name: run the build open ssl script
    shell: uname -a
    register: abc
  - name: show output
    debug: var=abc
